# This is a basic workflow to help you get started with Actions

name: make lint

on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - run: ls -la
      - run: make lint
